[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
#via_ir = true
remappings = [
    "@openzeppelin-contracts/contracts=lib/openzeppelin-contracts/contracts/",
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@ccip=lib/ccip/',
    '@chainlink-local=lib/chainlink-local/',
]

# Enable the following line to allow scripts to use `--ffi`
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[rpc_endpoints]
eth-sepolia = "${ETH_SEPOLIA_RPC_URL}"
arb-sepolia = "${ARB_SEPOLIA_RPC_URL}"
zksync-sepolia = "{ZKSYNC_SEPOLIA_RPC_URL}"

[invariant]
runs = 128
depth = 128
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
